### ISSUE TITLE
data set process

### ISSUE THREAD

**Issue by XipengY** [Tuyki/TT_RNN#1]
Hi, i want to know how to process the data set when you do experiment. such as experiment on UCF11 data set, giving the mpg video to the variable "data_path" directly? but i used the video directly, the code was crashed at this_clip = pickle.load(read_in)[0], and I have processed the data set to frame, and resized the image to 160×120×3, it also crashed at there, although generate a sequence of RGB frames of size 160 × 120 from each clip at an fps(frame per second) of 24 in paper, behind the code of crashed, there are some comment says "of shape (nb_frames, 240, 320, 3)", how do i understand it?
as it well, you have processed the mpg video to a tensor like (nb_frames, 240, 320, 3), and use the function pickle.load() to load the processed data?

**Comment by Tuyki** [comment]
Hi,

this is how I processed my data: 
1.	ffmpeg(raw_video) -> .jpeg
2.	scipy.imread(jpeg) -> numpy.ndarray
3.	pickle(numpy.ndarray) -> .pkl 
4.	train(numpy.ndarray)

What I load from the data_path is the pkl files storing the videos as numpy tensors. 

Hope it helps!

**Comment by XipengY** [comment]
Ok, thank you very much. it helps me.

**Comment by XiaonanHuang** [comment]
Hi,

I have some confusion in how to process the raw data(video) now.
Is it convenient for you to open or paste the code that you process the data? @Tuyki @XipengY 

thank you very much

**Comment by tzrtzr000** [comment]
same problem. Please update the code

**Comment by Tuyki** [comment]
As mentioned above, one could use ffmpeg to extract jpegs from a video, such as  
`ffmpeg -i video_name -vf "fps=24, scale=160:120" jpeg_name`. 
For more details please refer to the [documentation ](https://ffmpeg.org/ffmpeg.html)
